# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nathan Musoke's Personal Website
email: n.musoke@auckland.ac.nz
description: > # this means to ignore newlines until "baseurl:"
        Nathan Musoke's Personal Website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nathan.musoke.ca" # the base hostname & protocol for your site
include: ['_pages']

# Social media accounts for use later
twitter_username: NathanMusoke
github_username: musoke
linkedin_username: NathanMusoke
ORCID_identifier: 0000-0001-9839-9256
google_scholar_user: ll4tDj4AAAAJ
INSPIRE_BAI: N.Musoke.1 
arxiv_id: musoke_n_1 # http://arxiv.org/a/musoke_n_1.html
Researcher_ID: A-2604-2016 # ResearcherID: A-2604-2016
scopus_authour_id: 56010561500 # http://www.scopus.com/inward/authorDetails.url?authorID=56010561500&partnerID=MN8TOARS
academia.edu: https://auckland.academia.edu/NathanMusoke


# Build settings
markdown: kramdown
