# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nathan Musoke
email: n.musoke@auckland.ac.nz
description: > # this means to ignore newlines until "baseurl:"
        Nathan Musoke's Personal Website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nathan.musoke.ca" # the base hostname & protocol for your site

# Contact information for home page.
physical_address:
        - Department of Physics
        - University of Auckland
        - New Zealand

include: ['_pages']
exclude: ['*.sh']

# Build settings
markdown: kramdown
